// @ts-check

export default {
    lang: [`en`, `ru`],
    title: [`Minishoot' Adventures Map`, `Карта Minishoot' Adventures`],
    desc: [
        `The most complete <a target="blank" href="https://store.steampowered.com/app/1634860/">Minishoot' Adventures</a> map.`,
        `Самая полная карта <a target="blank" href="https://store.steampowered.com/app/1634860/">Minishoot' Adventures</a>.`
    ],
    desc2: [
        `This map contains every game object from the <i>v1</i> version of the game.`,
        `Карта содержит все игровые объекты из версии <i>v1</i> игры.`
    ],
    desc3: [
        `Source code is available on`,
        `Исходный код доступен на`
    ],
    map: [`Map`, `Карта`],
    object: [`Object`, `Объект`],
    filters: [`Filters`, `Фильтры`],
    about: [`About`, `О сайте`],
    sorry_js: [
        `Sorry, your browser doesn't support JavaScript`,
        `Извините, ваш браузер не поддерживает JavaScript`,
    ],
    sorry_webgl: [
        `Sorry, your browser doesn't support WebGL2`,
        `Извините, ваш браузер не поддердивает WebGL2`
    ],
    markers: ['Markers', 'Маркеры'],
    npcs: ['NPCs', 'NPC'],
    regkey: ['Regular keys', 'Обычные ключи'],
    bosskey: ['Boss keys', 'Ключи для боссов'],
    bossdropkey: ['Boss drop keys', 'Ключи с боссов'],
    uniquekey: ['Unique keys', 'Уникальные ключи'],
    module: ['Modules', 'Модули'],
    skill: ['Skills', 'Skills'],
    stats: ['Stats', 'Статы'],
    scarab: ['Scarabs', 'Скарабеи'],
    lore: ['Lore tablets', 'Lore tablets'],
    mappiece: ['Map pieces', 'Части карты'],
    enemy: ['Enemies', 'Враги'],
    filter_by_size: ['Filter by size', 'Отфильтровать по размеру'],
    filter_by_tier: ['Filter by tier', 'Отфильтровать по уровню'],
    jar: ['Jars', 'Горшки'],
    filter_by_drop: ['Filter by drop type', 'Отфильтровать по содержимому'],

    j0: ['nothing', 'ничего'],
    j2: ['random', 'случайное'],
    j3: ['big crystal', 'большой кристалл'],
    j4: ['energy', 'енергия'],
    j5: ['full energy', 'полная энергия'],
    j6: ['65 big crystals', '65 больших кристаллов'],

    crystal: ['Crystals', 'Кристаллы'],
    filter_by_xp: ['Filter by xp drop', 'Отфильтровать по наличию опыта'],
    transition: ['Transitions', 'Переходы'],
    tunnel: ['Tunnels', 'Туннели'],
    torch: ['Torches', 'Факела'],
    other: ['All other objects (a lot!)', 'Все остальные объекты (много!)'],
    background: ['Backgrounds', 'Фоны'],

    loading: ['Loading...', 'Загружается...'],
    loading_error: ['Loading error', 'Ошибка загрузки'],

    no: ['no', 'нет'],
    yes: ['yes', 'да'],
    more: ['more', 'больше'],
    name: ['Name', 'Название'],
    children: ['Children', 'Дочерние объекты'],
    parents: ['Parents', 'Родительские объекты'],
    no_selected: ['No object selected', 'Объект не выбран'],
    focus: ['Focus', 'Показать'],
    copyurl: ['Copy URL', 'Скопировать URL'],
    position: ['Position', 'Позиция'],
    components: ['Components', 'Компоненты'],
    referenced: ['Referenced by', 'Ссылки в других объектах'],
    localpos: ['Local position', 'Локальная позиция'],
    localscale: ['Local scale', 'Локальный размер'],
    localrot: ['Local rotation', 'Локальное вращение'],
    dropsxp: ['Drops XP', 'Содержит опыт'],
    size: ['Size', 'Размер'],
    inv: ['Invincible', 'Неуязвимый'],
    permanent: ['Permanent', 'Перманентный'],
    offset: ['Offset', 'Сдвиг'],
    radius: ['Radius', 'Радиус'],
    target: ['Target', 'Цель'],
    group: ['Group', 'Группа'],
    prereq: ['Prereqisute', 'Условие'],
    level: ['Level', 'Уровень'],
    price: ['Price', 'Цена'],
    forsale: ['For sale', 'Продаётся'],
    i_title: ['Title', 'Название'],
    i_desc: ['Description', 'Описание'],
    owner: ['Owner', 'Продваец'],
    dest: ['Destination', 'Куда'],
    droptype: ['Drop type', 'Тип дропа'],
    tier: ['Tier', 'Уровень'],
    away: ['away', 'в'],
    objnear: ['Objects nearby', 'Объекты поблизости'],
    m: ['m', 'м'],
} as const
